[package]
name = "zero-even-odd"
version = "0.1.0"
authors = ["Rajasekharan Vengalil <rajave@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
